name: Telegram Bot 24x7

on:
  schedule:
    - cron: "*/10 * * * *"   # Har 10 minutes me auto start
  workflow_dispatch:

concurrency:
  group: bot-runner
  cancel-in-progress: false   # Ye sabse important hai

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350      # 6h se pehle stop

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot==20.4

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python bot.py
